PERSONA_DESCRIPTION_MAX_LENGTH = 2000
MAX_CONVERSATION_EXAMPLES = 100
MAX_QUESTION_LENGTH = 500
MAX_ANSWER_LENGTH = 2000

DEFAULT_PERSONA_DATA = {
    "persona_description": "",
    "conversations": []
}