PERSONA_DESCRIPTION_MAX_LENGTH = 2000
MAX_CONVERSATION_EXAMPLES = 200
MAX_QUESTION_LENGTH = 1000
MIN_QUESTION_LENGTH = 100
MAX_ANSWER_LENGTH = 2000

DEFAULT_PERSONA_DATA = {
    "persona_description": "",
    "conversations": []
}