# Generated by Django 5.2 on 2025-04-26 09:23

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_image_path, verbose_name='Profile Image')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'custom_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=512)),
                ('file_category', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio')], max_length=10)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('thumbnail_path', models.CharField(blank=True, max_length=512, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=20, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Twin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('persona_data', models.JSONField(blank=True, default=core.models.Twin.get_default_persona_data, help_text='Structured persona data including description and conversation examples')),
                ('privacy_setting', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared', 'Shared with selected users')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediafile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Digital Twin',
                'verbose_name_plural': 'Digital Twins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwinAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('grant_expires', models.DateTimeField(blank=True, null=True)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='core.twin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTwinChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user_has_access', models.BooleanField(default=True)),
                ('twin_is_active', models.BooleanField(default=True)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.twin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=512)),
                ('duration_seconds', models.FloatField()),
                ('format', models.CharField(default='ogg', max_length=10)),
                ('sample_rate', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('transcription', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='core_voicer_created_80e4bb_btree')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_from_user', models.BooleanField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('file', 'File')], max_length=10)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_preview_url', models.URLField(blank=True, null=True)),
                ('file_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to='core.mediafile')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.usertwinchat')),
                ('voice_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.voicerecording')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='core_authto_token_434c69_idx'), models.Index(fields=['expires_at'], name='core_authto_expires_713117_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['uploader', 'uploaded_at'], name='core_mediaf_uploade_a91309_btree'),
        ),
        migrations.AddIndex(
            model_name='twin',
            index=models.Index(fields=['owner'], name='core_twin_owner_i_d6c67e_idx'),
        ),
        migrations.AddIndex(
            model_name='twin',
            index=models.Index(fields=['privacy_setting'], name='core_twin_privacy_0990fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='twinaccess',
            constraint=models.UniqueConstraint(fields=('user', 'twin'), name='unique_access_grant'),
        ),
        migrations.AddIndex(
            model_name='usertwinchat',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user', 'last_active'], name='core_usertw_user_id_b227e4_btree'),
        ),
        migrations.AddIndex(
            model_name='usertwinchat',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['twin', 'last_active'], name='core_usertw_twin_id_9d5014_btree'),
        ),
        migrations.AddConstraint(
            model_name='usertwinchat',
            constraint=models.UniqueConstraint(fields=('user', 'twin'), name='unique_user_twin_pair'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['chat', 'created_at'], name='core_messag_chat_id_e60b41_btree'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_from_user', 'created_at'], name='core_messag_is_from_964968_btree'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['status'], name='status_gin_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
