# Generated by Django 5.2 on 2025-04-21 09:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_image_path, verbose_name='Profile Image'),
        ),
    ]
