# Generated by Django 5.2 on 2025-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
