# Generated by Django 5.2 on 2025-05-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
