# Generated by Django 5.2 on 2025-05-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_subscription_is_resolved_contact_is_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecording',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
