# Generated by Django 5.2 on 2025-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_voicerecording_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='twinaccess',
            name='can_chat',
            field=models.BooleanField(default=False, help_text='Allow recipient to chat with this twin'),
        ),
        migrations.AddField(
            model_name='twinaccess',
            name='can_view_details',
            field=models.BooleanField(default=True, help_text='Allow recipient to view twin details'),
        ),
    ]
