# Generated by Django 5.2 on 2025-05-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_twinaccess_can_chat_twinaccess_can_view_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twinaccess',
            name='can_chat',
        ),
        migrations.RemoveField(
            model_name='twinaccess',
            name='can_view_details',
        ),
    ]
