# Generated by Django 5.2 on 2025-05-23 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_message_report_count_message_reply_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted', models.BooleanField(default=False)),
                ('theme', models.CharField(default='default', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.usertwinchat')),
            ],
            options={
                'verbose_name': 'Chat Settings',
                'verbose_name_plural': 'Chat Settings',
                'indexes': [models.Index(fields=['chat'], name='core_chatse_chat_id_fca649_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('inappropriate_behavior', 'Inappropriate Behavior'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.usertwinchat')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Report',
                'verbose_name_plural': 'Contact Reports',
                'indexes': [models.Index(fields=['chat'], name='core_contac_chat_id_23bddb_idx'), models.Index(fields=['created_at'], name='core_contac_created_7d14f8_idx')],
            },
        ),
    ]
