# Generated by Django 5.2 on 2025-05-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatsettings_contactreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwinchat',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
