# Generated by Django 5.2 on 2025-05-26 09:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usertwinchat_is_archived'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='status_gin_trgm',
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['status'], name='status_gin_idx'),
        ),
    ]
