# Generated by Django 5.2 on 2025-05-26 09:48

from django.db import migrations
from django.contrib.postgres.indexes import GinIndex, OpClass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usertwinchat_is_archived'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='status_gin_trgm',
        ),
        migrations.AddIndex(
            model_name='message',
            index=GinIndex(
                fields=[OpClass('status', 'gin_trgm_ops')],
                name='status_gin_idx',
            ),
        ),
    ]
