# Generated by Django 5.2 on 2025-05-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usertwinchat_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='twin',
            name='sentiment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twin',
            name='twin_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
