# Generated by Django 5.2 on 2025-05-26 09:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_message_status_gin_trgm_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='status_gin_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['status'], name='status_gin_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
